from tkinter import *
from tkinter import ttk
root = Tk()
frm = ttk.Frame(root, padding=10)
frm.grid()
box1 = Listbox(root, borderwidth=0, background='white')
box1.grid(column=0, row=2)
box2 = Listbox(root, borderwidth=0, background='white')
box2.grid(column=0, row=3)
box3 = Listbox(root, borderwidth=0, background='white')
box3.grid(column=0, row=4)
box4 = Listbox(root, borderwidth=0, background='white')
box4.grid(column=1, row=2)
box5 = Listbox(root, borderwidth=0, background='white')
box5.grid(column=1, row=3)
box6 = Listbox(root, borderwidth=0, background='white')
box6.grid(column=1, row=4)
box7 = Listbox(root, borderwidth=0, background='white')
box7.grid(column=2, row=2)
box8 = Listbox(root, borderwidth=0, background='white')
box8.grid(column=2, row=3)
box9 = Listbox(root, borderwidth=0, background='white')
box9.grid(column=2, row=4)
ttk.Button(frm, text="Quit", command=root.destroy).grid(column=1, row=0)
root.mainloop()